### ISSUE TITLE
Request for feedback on transition guide

### ISSUE THREAD

**Issue by adrn** [OpenAstronomy/python-3-for-scientists#1]
https://github.com/OpenAstronomy/python-3-for-scientists/blob/master/python3_user_transition_guide.rst

**Comment by astrofrog** [comment]
Thanks for working on this! A few small comments:

> any new code you write should be Python 3 compatible

I don't think we want to sound like we are forcing people - how about 'any new code you write _can easily be_ Python 3 compatible?

> `unicode_literals`

I've heard some people say this is probably not a good idea. Most packages will be able to deal with string in Python 2 and unicode in Python 3. So I would vote to actually remove this, and focus on the three other imports (I _never_ use unicode_literals, and many of my scripts are 2/3 compatible). In some cases, this can even cause issues, because some packages won't be expecting unicode in Python 2.

> A slightly more annoying issue is that several of the standard library Python packages have been reorganized or moved. Most of the changes were made to fairly obscure packages (full list here), but there are a few notable changes:

You didn't provide a way to deal with these changes if they want to keep Python 2 compatibility - maybe you can just mention in a single line that they can use the `six` package, and show the equivalent imports?

For the conda environments, note that also when people open a new terminal it will default to root again. Maybe you can mention how to get it to go to a certain environment by default.

> Identify Python 3 incompatibilities and automatically update them

How about simply 'Upgrading existing Python 2 code'? Also, maybe you can move that up before the conda env stuff? (then it's py3 code, upgrading py2, and using 2 and 3)

> Advanced: Writing code that is compatible with Python 2 and 3

This is also somewhat the purpose of the first section.

One thought on how to make it even more approachable: make a first section called 'Changes you can make **today** to make the transition easier later' (or something similar). This would just be the future imports. We want to catch people's attention and say 'these are things you can do right now and the cost is really low'. Then after the bit about the division you could start a new section that says 'Other main changes in Python 3' or something like this?

General comment: avoid use of `I` - because it will make it sound like the pages were written by a single person.

**Comment by adrn** [comment]
Thanks @astrofrog ! I've implemented these changes now. I guess I really should've filed a PR to make commenting easier...

**Comment by stephtdouglas** [comment]
But wait, here are a few more! :-P It's looking good, these are just a couple minor things

> Thankfully, the most disruptive changes to the language have been back-ported to Python 2 so you can ensure that, when writing Python 2-style code, it will be executable in Python 3... It is generally recommended that, if you are still writing Python 2 compatible code...

This is a little unclear. I think you're getting at two different use-cases - Python 2 code that will still be executable upon switching to Python 3, and Python 3 code that can be run under Python 2. It would be good to make the two cases explicit - the **future** line means less work re-writing code once you switch from 2 to 3, and it also means that once you switch to Python 3, your collaborators still using Python 2 can use your code as well. 

Maybe also link to more info about **future**?

You mention including absolute_imports in your **future** imports line, but it's not clear what that is. Could you add a note the way you did with division and the print function, or at least a link to a longer discussion of why absolute_imports is necessary? Is it really a general user thing, or should it just go under the dev pages?

Are there easy options for non-permanent upgrading if people use other distributions (i.e. Enthought)? Even just links would be good. If not, maybe it's worth noting that they can use Anaconda for this anyway - install it but don't let it be the default version, so it won't interfere with a previously installed version (I think this should work?).

**Comment by adrn** [comment]
> Are there easy options for non-permanent upgrading if people use other distributions (i.e. Enthought)? 

I actually don't know -- @astrofrog? @ngoldbaum?

**Comment by ngoldbaum** [comment]
You can simultaneously have a python2 and python3 installation on the same system. That's what I do for homebrew. I have no idea how or if that would work for Enthought Canopy.

**Comment by adrn** [comment]
If there is a way with Canopy, someone else can make a PR to add that! In the meantime I added a line to suggest installing anaconda to try Python 3 in a fresh environment even if they are using another Python distro.

Any final comments @astrofrog or @stephtdouglas ?

**Comment by stephtdouglas** [comment]
There are only three "must" imports from future now, not four, but aside from that I think you're good to go!

**Comment by astrofrog** [comment]
In MacPorts it's definitely possible, I can write that. How about we make a page specifically about setting up Python 2 and 3 simultaneously, and we can have one section per tool, with conda at the top?

**Comment by astrofrog** [comment]
@adrn - no other comments from me for now :) If I have any other comments in future, I'll just open a PR you can review first.
